name: Trigger Website Rebuild

on:
  push:
    branches: [main]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild in concordia-cash/concordia-cash.github.io repo
        run: |
          curl -X POST https://api.github.com/repos/concordia-cash/concordia-cash.github.io/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.WEBSITE_DISPATCH_TOKEN }}" \
            -d '{"event_type": "rebuild"}'
